---
title: "65_percent_readership"
format: html

---

```{r}
#| label: load-and-prep
#| echo: true
#| message: false

library(tidyverse)
library(readxl)
library(ggplot2)
library(scales)
library(lubridate)
library(glue)
library(ggtext)

roster_file <- dir(path = "~/OneDrive - NJASAP/Documents/Contact List UnionWare Aptify",
                     full.names = T,
                     pattern = "ACTIVE.*\\.xlsx$")

roster <- read_excel(roster_file,
                     sheet = "Sheet1",
                     range = cell_cols(1:25)
                     )

pull_date <- ymd("2024-05-27")

clean_roster <- roster %>%
  rename_with(~tolower(gsub(" ","_", .x))) %>% 
  rename(employee_no = `employee_#`,
         cmi = crew_member_id) %>% 
  mutate(hire_date = ymd(hire_date),
         end_date = ymd(end_date),
         birthday = ymd(birthday),
         full_name = as.character(glue("{last_name}, {first_name}")),
         yos = ceiling(as.duration(hire_date %--% today()) / dyears(1)),
         age = ceiling(as.duration(birthday %--% today()) / dyears(1)),
         hire_ym = as.character(glue("{year(hire_date)}-{str_pad(month(hire_date),2,pad = '0')}")),
         end_ym = ifelse(is.na(end_date),NA,
                          as.character(glue("{year(end_date)}-{str_pad(month(end_date),2,pad = '0')}"))
                          ),
         end_year_yy = str_sub(end_ym, start = -5, end = -4),
         hire_year_yy = str_sub(hire_ym, start = -5, end = -4),
         pull_date = pull_date
        )

 ### Required Dates ###

roster_max_pull_floor <- floor_date(max(clean_roster$pull_date, na.rm = T), months(1))

roster_12m_lb <- add_with_rollback(roster_max_pull_floor,
                                   months(-11))

rm(roster)
rm(roster_file)

### Name Lists from Message Board ###

name_list_file <- dir("~/OneDrive - NJASAP/_Action NJASAP",
                      full.names = T,
                      pattern = "2024-05-27 65 Percent Thread Stats.xlsx")

tname_list <- read_excel(name_list_file,
                         sheet = "Join",
                         range = cell_cols(1:5)
                         )

# tname_list <- tname_list %>% 
#   rename_all(tolower) %>% 
#   mutate(last_name = str_match(name, "[^ ]+$"),
#          last_fi = as.character(glue("{last_name} {str_sub(name, 1, 3)}"))) %>%
#   filter(! last_fi %in% c("Hammons Jam", "Spencer Ric")) %>% 
#   select(last_fi, name)

tname_list <- tname_list %>% 
  rename_all(tolower) %>% 
  mutate(across(email, ~tolower(email))) %>% 
  select(name, email)

rm(name_list_file)

```

```{r}
#| echo: true
#| label: data_stuff
#| message: false

### Create Join ###

troster_to_join <- clean_roster %>% 
  filter(is.na(end_date)) %>% 
  mutate(across(personal_email, ~tolower(personal_email))) %>% 
  select(full_name, hire_date, yos, age, aircraft, seat, personal_email)

tname_list_join <- tname_list %>% 
  left_join(troster_to_join, by = c("email" = "personal_email")) %>% 
  filter(is.na(yos))

```


```{r}
#| label: thread_readership
#| message: false

tname_list_join %>% 
  filter(!is.na(yos)) %>% 
  mutate(longevity = ifelse(yos <= 4, "llp", "non-llp")) %>% 
  count(longevity, name = "count") %>% 
  mutate(pct_viewed = label_percent(accuracy = 0.1) (count / sum(count))) %>% 
  ggplot(aes(longevity, count))+
  geom_col(fill = "steelblue") + 
  geom_text(aes(label = glue("{count} ({pct_viewed})")), vjust = -0.5)+
  scale_x_discrete(labels = c("llp" = "LLP",
                                      "non-llp" = "Non-LLP")
                  )+
  theme_bw()+
  labs(x = NULL,
       y = "Count",
       title = "'65 Percent' Readership Distribution",
       subtitle = NULL,
       fill = NULL
  )
```


```{r}
clean_roster %>% 
  filter(str_detect(job_status, "^Active")) %>% 
  mutate(longevity = ifelse(yos <= 4, "llp", "non-llp")) %>% 
  count(longevity, name = "count") %>% 
  mutate(pct_viewed = label_percent(accuracy = 0.1) (count / sum(count))) %>% 
  ggplot(aes(longevity, count))+
  geom_col(fill = "steelblue") + 
  geom_text(aes(label = glue("{count} ({pct_viewed})")), vjust = -0.5)+
  theme_bw()+
  scale_x_discrete(labels = c("llp" = "LLP",
                                      "non-llp" = "Non-LLP")
                  )+
  labs(x = NULL,
       y = "Count",
       title = "Total Population Distribution",
       subtitle = "*LLP defined as four years or less YOS*",
       fill = NULL
  )+
  theme(plot.title = element_markdown(),
          plot.subtitle = element_markdown()
    )

```


```{r}
tname_list_join %>% 
  filter(!is.na(yos)) %>% 
  count(yos, name = "count") %>% 
  ggplot(aes(yos, count))+
  geom_col(fill = "steelblue") + 
  geom_text(aes(label = count),vjust = -0.5)+
  theme_bw()+
  scale_x_continuous(n.breaks = 25)+
  labs(x = NULL,
       Y = "Count",
       title = "Readership Distribution by YOS")+
  theme(plot.title = element_markdown())
```    